### PR TITLE
Add support to xxxhdpi.

### PR DESCRIPTION
**Pull request by lrcosta**

### CODE REVIEW

**Comment by dogo** [comment]
+1

**Comment by mgohin** [comment]
I was about to make the same PR :p so +1

**Comment by vincenzo-petronio** [comment]
+1

**Comment by PavelTschors** [comment]
+1. And we probably don't need ldpi anymore.

**Comment by gastonfig** [comment]
Thanks for bringing this up. Completely agree with adding xxxhdpi and deprecating ldpi. I've started working on some improvements in addition to these changes and should be able to release something in the next days.

**Pull request closed without merging**
